name: 'David504CI'
description: 'To load and run tests from a pharo project'
inputs:
  removes-repo:  # id of input
    description: 'Name of packages to remove'
    required: false
    default: '.' # if default it will not remove anything
  baseline:  # id of input
    description: 'The baseline name of the project to test'
    required: true
    default: '.'
  group:  # id of input
    description: 'The baseline group to load'
    required: false
    default: 'default'
  tests: # id of input
    description: 'A string to run a group of tests, separated by commas'
    required: true
    default: '.'
  pharo: # id of input
    description: 'A pharo version, can be pharo9, pharo10 or pharo11'
    required: false
    default: '64/alpha+vm'

outputs:
  time: # id of output
    description: 'The current time'
runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: 'activity'
  color: 'green'