name: 'Pharo CI'
description: 'To load and run tests from a pharo project'
inputs:
  repo:  # id of input
    description: 'Package'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The current time'
runs:
  using: 'node12'
  main: 'index.js'