on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test pharo code
    steps:
    - name: Run pharo Tests
      id: tests
      uses: akevalion/PharoTestsAction@v1
      with:
        removes-repo: 'roassal, numberic'