on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to tests code
    steps:
    - name: Run pharo Tests
      id: tests
      uses: akevalion/PharoTestsAction@v1
      with:
        removes-repo: 'roassal, numberic'
    - name: Get the output
      run: echo -e "\e[31mRed Text\e[0m \e[32mGreen Text\e[0m"